[package]
name = "sigil"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
sha2 = "0.10"
chrono = "0.4"
reed-solomon = "0.2"
pqcrypto-kyber = "0.7"
rayon = "1.5"
parquet = "0.21"
arrow = "0.21"  # For Parquet compatibility
